# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t6FupanNTF9Do7gPZhekGKMCQaVVPEK6
"""

import pandas as pd
import numpy as np
from google.colab import files

# 1. توليد البيانات (Data Generation)
np.random.seed(42)
n_rows = 300
categories = ['Marketing', 'IT', 'Operations', 'Sales', 'HR']

data = {
    'Date': pd.date_range(start='2025-01-01', periods=n_rows, freq='D'),
    'Category': np.random.choice(categories, n_rows),
    'Budget': np.random.uniform(5000, 20000, n_rows).round(2),
    'Actual_Spending': np.random.uniform(4000, 22000, n_rows).round(2)
}

df = pd.DataFrame(data)

# 2. تنظيف البيانات (Data Cleaning)
df.drop_duplicates(inplace=True)
df['Actual_Spending'] = df['Actual_Spending'].abs() # تحويل أي قيم سالبة بالخطأ

# 3. الحسابات المتقدمة - بدلاً من DAX (Feature Engineering)
# حساب الفرق المالي
df['Variance'] = (df['Budget'] - df['Actual_Spending']).round(2)

# حساب نسبة الميزانية المستهلكة
df['Spending_Ratio_%'] = ((df['Actual_Spending'] / df['Budget']) * 100).round(2)

# تحديد حالة القسم (Over Budget أو Within Budget)
df['Status'] = df['Variance'].apply(lambda x: 'Over Budget' if x < 0 else 'Within Budget')

# إضافة عمود الشهر والسنة لتسهيل الفلترة في Power BI
df['Month'] = df['Date'].dt.month_name()
df['Year'] = df['Date'].dt.year

# 4. حفظ وتحميل الملف النهائي
file_name = 'PowerBI_Final_Project.csv'
df.to_csv(file_name, index=False)
files.download(file_name)

print("✅ تم بنجاح: توليد، تنظيف، وحساب البيانات. الملف جاهز للتحميل الآن!")